dist: precise
language: node_js
node_js:
  - "node"
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
before_script:
  - npm install
script:
  - npm run test
  - npm run build
